# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I Made This
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's taken some time but this small part of the internet is set aside to log and write about the things I create. These 'things' can involve eidible creations, tactile (typically craft in nature) and non tactile creations (typically code driven).

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kaseylmccormick
github_username:  /kaseymccormick

# Build settings
markdown: kramdown
